In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('cars.csv')
df.head()

symboling normalized-losses         make fuel-type   body-style  \
0          3                 ?  alfa-romero       gas  convertible   
1          3                 ?  alfa-romero       gas  convertible   
2          1                 ?  alfa-romero       gas    hatchback   
3          2               164         audi       gas        sedan   
4          2               164         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500  
2        154        19           26  16500  
3        102        24           30  13950  
4        115        18           22  17450

In [3]:
df['normalized-losses'].replace('?',np.nan,inplace=True)
df['horsepower'].replace('?',np.nan,inplace=True)
df["normalized-losses"]= df["normalized-losses"].astype('float')
df['horsepower'] = df['horsepower'].astype('float')
nmean = df['normalized-losses'].mean()
hmean = df['horsepower'].mean() 
df['normalized-losses'].fillna(nmean,inplace=True)
df['horsepower'].fillna(hmean,inplace=True)

In [4]:
df.head()

symboling  normalized-losses         make fuel-type   body-style  \
0          3              122.0  alfa-romero       gas  convertible   
1          3              122.0  alfa-romero       gas  convertible   
2          1              122.0  alfa-romero       gas    hatchback   
3          2              164.0         audi       gas        sedan   
4          2              164.0         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

   horsepower  city-mpg  highway-mpg  price  
0       111.0        21           27  13495  
1       111.0        21           27  16500  
2       154.0        19           26  16500  
3       102.0        24           30  13950  
4       115.0        18           22  17450

In [5]:
df_cat = df.select_dtypes(object)
df_num = df.select_dtypes('int64','float64')

In [6]:
df_cat

make fuel-type   body-style drive-wheels engine-location  \
0    alfa-romero       gas  convertible          rwd           front   
1    alfa-romero       gas  convertible          rwd           front   
2    alfa-romero       gas    hatchback          rwd           front   
3           audi       gas        sedan          fwd           front   
4           audi       gas        sedan          4wd           front   
..           ...       ...          ...          ...             ...   
200        volvo       gas        sedan          rwd           front   
201        volvo       gas        sedan          rwd           front   
202        volvo       gas        sedan          rwd           front   
203        volvo    diesel        sedan          rwd           front   
204        volvo       gas        sedan          rwd           front   

    engine-type  
0          dohc  
1          dohc  
2          ohcv  
3           ohc  
4           ohc  
..          ...  
200         ohc  
201         ohc  
202        ohcv  
203         ohc  
204         ohc  

[205 rows x 6 columns]

In [7]:
df_num

symboling  engine-size  city-mpg  highway-mpg  price
0            3          130        21           27  13495
1            3          130        21           27  16500
2            1          152        19           26  16500
3            2          109        24           30  13950
4            2          136        18           22  17450
..         ...          ...       ...          ...    ...
200         -1          141        23           28  16845
201         -1          141        19           25  19045
202         -1          173        18           23  21485
203         -1          145        26           27  22470
204         -1          141        19           25  22625

[205 rows x 5 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder
for col in df_cat:
    le= LabelEncoder()
    df_cat[col] = le.fit_transform(df_cat[col])

In [9]:
df_cat[col]

0      0
1      0
2      5
3      3
4      3
      ..
200    3
201    3
202    5
203    3
204    3
Name: engine-type, Length: 205, dtype: int32

In [10]:
from scipy.stats import skew
df = pd.concat([df_cat,df_num],axis=1)

In [11]:
df

make  fuel-type  body-style  drive-wheels  engine-location  engine-type  \
0       0          1           0             2                0            0   
1       0          1           0             2                0            0   
2       0          1           2             2                0            5   
3       1          1           3             1                0            3   
4       1          1           3             0                0            3   
..    ...        ...         ...           ...              ...          ...   
200    21          1           3             2                0            3   
201    21          1           3             2                0            3   
202    21          1           3             2                0            5   
203    21          0           3             2                0            3   
204    21          1           3             2                0            3   

     symboling  engine-size  city-mpg  highway-mpg  price  
0            3          130        21           27  13495  
1            3          130        21           27  16500  
2            1          152        19           26  16500  
3            2          109        24           30  13950  
4            2          136        18           22  17450  
..         ...          ...       ...          ...    ...  
200         -1          141        23           28  16845  
201         -1          141        19           25  19045  
202         -1          173        18           23  21485  
203         -1          145        26           27  22470  
204         -1          141        19           25  22625  

[205 rows x 11 columns]

In [12]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [13]:
x

make  fuel-type  body-style  drive-wheels  engine-location  engine-type  \
0       0          1           0             2                0            0   
1       0          1           0             2                0            0   
2       0          1           2             2                0            5   
3       1          1           3             1                0            3   
4       1          1           3             0                0            3   
..    ...        ...         ...           ...              ...          ...   
200    21          1           3             2                0            3   
201    21          1           3             2                0            3   
202    21          1           3             2                0            5   
203    21          0           3             2                0            3   
204    21          1           3             2                0            3   

     symboling  engine-size  city-mpg  highway-mpg  
0            3          130        21           27  
1            3          130        21           27  
2            1          152        19           26  
3            2          109        24           30  
4            2          136        18           22  
..         ...          ...       ...          ...  
200         -1          141        23           28  
201         -1          141        19           25  
202         -1          173        18           23  
203         -1          145        26           27  
204         -1          141        19           25  

[205 rows x 10 columns]

In [14]:
y

0      13495
1      16500
2      16500
3      13950
4      17450
       ...  
200    16845
201    19045
202    21485
203    22470
204    22625
Name: price, Length: 205, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=1)

In [16]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(xtrain,ytrain)
ypred = linreg.predict(xtest)
ypred

array([ 5962.97758515,  7795.60210689,  4661.8163169 ,  6647.7615444 ,
       11216.36292043, 25861.11513988,  6451.92083709,   588.44175869,
        4661.8163169 , 12197.23643684, 15779.14257674, 13493.02617536,
       15706.47960157, 10827.23900612, 17855.42694534, 13882.15008968,
        8636.88449056,  9039.9790604 ,  9750.77598927,  8326.56169503,
       10164.75007358,  7071.08068147, 14260.55032905,  8383.61356728,
       14271.274004  ,  9039.9790604 , 16562.63999963,  5581.83192918,
        5368.15487795,  9605.41250157,  8984.61553857, 13966.28717408,
       26850.21161104, 11851.51723139, 18858.32518375,  5581.83192918,
       10619.57597546, 31653.05841021, 11167.0527886 , 15439.46183169,
        6541.2410591 , 21277.98743197,  8107.52391842,  9740.64810843,
        7464.89648205,  7017.35427826, 39424.49792501,  6584.79831721,
       15925.03154554, 20065.96812385, 24906.55778439, 14693.07509603,
       21379.87215569,  7095.86396445, 11631.80299568,  6812.68917824,
      

In [17]:
from sklearn.metrics import mean_absolute_error as mae, mean_squared_error as mse, r2_score

print(f'mae = {mae(ytest,ypred)}')
print(f'mse = {mse(ytest,ypred)}')
print(f'rmse = {np.sqrt(mse(ytest,ypred))}')
print(f'Accuracy = {r2_score(ytest,ypred)}')

mae = 2487.468693863707
mse = 12082948.392250719
rmse = 3476.053565791344
Accuracy = 0.7994858482839375


In [18]:
linreg.score(xtrain,ytrain)

0.8243563647365482

In [19]:
from sklearn.linear_model import Ridge,Lasso

In [20]:
L1= Lasso(alpha = 10)
L1.fit(xtrain,ytrain)
ypred= L1.predict(xtest)
ypred

array([ 6013.06259276,  7762.02719764,  4735.81570267,  6620.87553433,
       11208.44241188, 25738.38932539,  6534.06493279,   591.20451393,
        4735.81570267, 12208.87380319, 15786.50289899, 13634.87121374,
       15666.38065601, 10857.83563611, 17905.25750775, 13985.4779895 ,
        8694.7723218 ,  9027.9354414 ,  9847.52398851,  8373.97728721,
       10198.15974071,  7103.10421349, 14197.67319308,  8426.79041636,
       14336.08476527,  9027.9354414 , 16633.54228356,  5550.97778149,
        5425.17549261,  9554.68415472,  8955.38398516, 13925.12260561,
       26877.40853718, 11883.81709912, 18757.04799124,  5550.97778149,
       10594.13322668, 31725.86083508, 11128.34990786, 15461.26376664,
        6584.3283701 , 21341.47235636,  8009.35913119,  9725.02592203,
        7515.78822038,  7060.81364611, 39500.32710788,  6624.72122701,
       15919.44856733, 20130.61422207, 24861.0338363 , 14660.75028922,
       21353.73228485,  7119.55976183, 11682.12508987,  6815.28956893,
      

In [21]:
r2_score(ytest,ypred)

0.8008993858284892

In [22]:
L2 = Ridge(alpha = 6)
L2.fit(xtrain,ytrain)
ypred = L2.predict(xtest)
ypred

array([ 6485.78042826,  7462.9342755 ,  5412.99023057,  6330.08704454,
       11000.42060489, 24952.79579885,  7273.73032483,   445.98849946,
        5412.99023057, 12208.75400086, 15504.37608669, 15251.06907852,
       15521.18369378, 10973.50483008, 18395.67104834, 15277.98485333,
        9330.30237053,  8792.26823069, 10344.44659773,  8603.10355674,
       10406.42429501,  7371.71554619, 13734.68109302,  8753.56933436,
       15304.90062815,  8792.26823069, 17362.08007742,  5616.21750439,
        5912.24953479,  8927.64063173,  8982.8596414 , 13369.11219503,
       27325.45744376, 12171.12308203, 18109.57404613,  5616.21750439,
       10257.04363906, 32171.38584837, 11524.38338692, 15850.23062677,
        7185.98453892, 22528.30736021,  7345.41780226,  9709.45464594,
        8084.18795469,  7409.10272587, 40830.20726947,  6917.69463309,
       15897.33021786, 21002.09163371, 24790.507623  , 14371.98092476,
       21335.29856143,  7281.93770811, 12073.38159983,  6746.13882869,
      

In [23]:
r2_score(ytest,ypred)

0.8092617108108753

In [24]:
for i in range(1,101):
    L2=Ridge(alpha = i)
    L2.fit(xtrain,ytrain)
    ypred = L2.predict(xtest)
    print(f'{i}-: {L2.score(xtest,ytest)}')

1-: 0.8054342911882846
2-: 0.80768340527485
3-: 0.80868159029648
4-: 0.8091240091489911
5-: 0.8092765052270021
6-: 0.8092617108108753
7-: 0.8091439085005185
8-: 0.8089600141604766
9-: 0.8087327021703581
10-: 0.8084766238081287
11-: 0.8082016211007355
12-: 0.8079145070078877
13-: 0.8076201085441282
14-: 0.8073219070467827
15-: 0.807022446728277
16-: 0.8067236040791358
17-: 0.806426770575191
18-: 0.8061329796256681
19-: 0.8058429966530859
20-: 0.8055573841964556
21-: 0.8052765497267576
22-: 0.8050007812662479
23-: 0.8047302742558083
24-: 0.8044651520452399
25-: 0.8042054816726797
26-: 0.8039512861205812
27-: 0.8037025539066998
28-: 0.803459246638828
29-: 0.803221304999326
30-: 0.802988653508695
31-: 0.8027612043325671
32-: 0.8025388603341026
33-: 0.8023215175274342
34-: 0.8021090670530457
35-: 0.8019013967696517
36-: 0.8016983925370539
37-: 0.801499939249003
38-: 0.8013059216630971
39-: 0.8011162250654065
40-: 0.8009307358001645
41-: 0.8007493416890585
42-: 0.8005719323600414
43-: 0.8003

In [27]:
for i in range(101,1001,50):
    L1=Lasso(alpha = i)
    L1.fit(xtrain,ytrain)
    ypred = L1.predict(xtest)
    print(f'{i}-: {L1.score(xtest,ytest)}')

101-: 0.8080757200599453
151-: 0.8076932174748208
201-: 0.804911333199987
251-: 0.8004041426258897
301-: 0.7967124206251738
351-: 0.7923126894873813
401-: 0.7877978969845967
451-: 0.7850561661600761
501-: 0.7849815015383479
551-: 0.7849007538605837
601-: 0.7848139638401673
651-: 0.784721086082955
701-: 0.7846221317387714
751-: 0.7845170872532512
801-: 0.7844059526263947
851-: 0.7842893560401039
901-: 0.7841659703725582
951-: 0.7840364885503537


In [28]:
L1= Lasso(alpha = 150)
L1.fit(xtrain,ytrain)
ypred= L1.predict(xtest)
ypred

array([ 6673.54073441,  7558.21681178,  5648.1384932 ,  6369.86833294,
       11088.64932983, 23962.15490349,  7460.98505076,   676.49998435,
        5648.1384932 , 12363.73363049, 15950.09182594, 15252.76810989,
       15262.18393954, 11088.64932983, 18624.0169599 , 15252.76810989,
        9507.93437255,  8749.23819347, 11174.37865791,  8946.34488946,
       10595.04842855,  7515.51623608, 13338.34065112,  8873.73259521,
       15252.76810989,  8749.23819347, 17641.71220795,  5236.72955547,
        6102.16233312,  8846.4699545 ,  8664.09162021, 13442.95755785,
       27315.63550925, 12492.78935766, 17361.15460137,  5236.72955547,
       10277.025098  , 32833.98022606, 10576.1324175 , 15696.43677673,
        7152.57067752, 22167.0719179 ,  6751.632044  ,  9662.26542045,
        8356.71830993,  7558.21681178, 40695.87262364,  7067.94904053,
       15840.65456983, 21029.32802742, 23864.92314246, 14205.67764476,
       21114.26669735,  7427.96777442, 12266.50186947,  6790.85608378,
      

In [30]:
r2_score(ytest,ypred)

0.8077246305279036

In [33]:
from sklearn.model_selection import cross_val_score

cvs = cross_val_score(L2,x,y,cv=5)
cvs

array([0.79048989, 0.83856722, 0.19808905, 0.58159777, 0.31262039])

In [34]:
cvs.mean()

0.5442728637268947

In [35]:
from sklearn.model_selection import cross_val_score

cvs = cross_val_score(L1,x,y,cv=5)
cvs

array([0.79286143, 0.84181694, 0.2263928 , 0.55616587, 0.31705056])

In [36]:
cvs.mean()

0.5468575190944732